name: Tracker
version: 1.0
author: Zeeppss
description: Player Track Request From Naga 
main: dev.zeeppss.tracker.Main
api-version : 1.8
commands:
  track:
    description: List Command for Player Tracker.
  tracker:
    description: Gui menu for buy tracker.
